---
- name: render meta-data
  template:
    src: meta-data.j2
    dest: "{{ provision_kvm_guest_machine_folder }}/meta-data"
  tags:
    - cloud-init
    - meta-data

- name: render user-data
  template:
    src: user-data.j2
    dest: "{{ provision_kvm_guest_machine_folder }}/user-data"
  tags:
    - cloud-init
    - user-data

- name: render network-config
  template:
    src: network-config.j2
    dest: "{{ provision_kvm_guest_machine_folder }}/network-config"
  tags:
    - cloud-init
    - network-config
