---

- name: render meta-data
  template:
    src: meta-data.j2
    dest: "{{ armlab_provision_machine_folder }}/{{ armlab_provision_hostname }}-meta-data"
  tags:
    - cloud-init
    - meta-data

- name: render user-data
  template:
    src: user-data.j2
    dest: "{{ armlab_provision_machine_folder }}/{{ armlab_provision_hostname }}-user-data"
  tags:
    - cloud-init
    - user-data
