---
# defaults file for provision-kvm-guest
provision_kvm_guest_cloud_init: lanecloud
provision_kvm_guest_nocloud_base_url: "https://example.com/nocloud"
provision_kvm_guest_nocloud_url: "{{ provision_kvm_guest_nocloud_base_url }}/{{ provision_kvm_guest_cloud_init }}/"
provision_kvm_guest_hostname: CHANGEME
provision_kvm_guest_mac_address: "{{ '52:58:00' | community.general.random_mac(seed=provision_kvm_guest_hostname) }}"
provision_kvm_guest_instance_id: "armlab-{{ provision_kvm_guest_hostname }}"
provision_kvm_guest_image_folder: /mnt/zfs/crucial/images
provision_kvm_guest_machines_base: /mnt/zfs/crucial/machines
provision_kvm_guest_machine_folder: "{{ provision_kvm_guest_machines_base }}/{{ provision_kvm_guest_hostname }}"
provision_kvm_guest_image_format: qcow2
provision_kvm_guest_image_file: "{{ provision_kvm_guest_hostname }}.img.{{ provision_kvm_guest_image_format }}"
provision_kvm_guest_image_size: 30G
provision_kvm_guest_smp: 2
provision_kvm_guest_memory: 2048
# provision_kvm_guest_base_image: debian-13-generic-arm64-daily.qcow2
provision_kvm_guest_base_image: Armbian-unofficial_24.05.23-armsurvivors-191_Uefi-arm64_bookworm_edge_6.8.10-metadata-cloud.img.qcow2
